# Taskfile - コミット・push 前のチェックを手動実行する用
# 使い方: コミット前に task pre-commit / push 前に task pre-push
version: '3'

tasks:
  default:
    desc: 利用可能なタスク一覧を表示
    cmds:
      - task --list

  # コミット前に実行: ステージ済みファイルに ESLint + Prettier
  pre-commit:
    desc: コミット前に実行（lint-staged）
    cmds:
      - pnpm exec lint-staged

  # push 前に実行: 保護ブランチへの直接 push を警告
  pre-push:
    desc: push 前に実行（保護ブランチチェック）
    cmds:
      - |
        BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
        if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
          echo ""
          echo "⚠️  警告: 保護ブランチ '$BRANCH' への直接 push です。"
          echo "   feature ブランチを作成してから push することを推奨します。"
          echo ""
          exit 1
        fi

  # 両方まとめて実行（コミット＆push 前の確認用）
  check-before-push:
    desc: pre-commit と pre-push を順に実行
    cmds:
      - task: pre-commit
      - task: pre-push

  # Supabase ローカル起動（認証用）。Docker が起動している必要あり
  supabase-start:
    desc: Supabase をローカルで起動（Auth, Studio 等）
    cmds:
      - pnpm supabase start

  supabase-stop:
    desc: Supabase ローカルを停止
    cmds:
      - pnpm supabase stop

  # Metro / Expo バンドラーを停止（ポート 8081 使用プロセスを終了。dev-up-emulator 前に実行すると .env が確実に読み直される）
  metro-stop:
    desc: Metro / Expo のバンドラーを停止（ポート 8081）
    cmds:
      - |
        if command -v lsof >/dev/null 2>&1; then
          PIDS=$(lsof -ti:8081 2>/dev/null) || true
          if [ -n "$PIDS" ]; then
            echo "Metro (port 8081) を停止します: $PIDS"
            echo "$PIDS" | xargs kill -9 2>/dev/null || true
          else
            echo "ポート 8081 で動作中のプロセスはありません。"
          fi
        else
          echo "lsof が見つかりません。手動で Metro/Expo を終了してください。"
        fi

  # 開発環境をまとめて起動（Expo は含まない。別ターミナルで task expo-start）
  # 注意: "container name already in use" が出たら docker rm -f sleepsupport-db sleepsupport-api してから再実行

  # Expo 開発サーバーを起動（別ターミナルで実行。.env.expo.local を読む）
  expo-start:
    desc: Expo 開発サーバーを起動（pnpm start）
    cmds:
      - pnpm start

  # Android で Development Build をビルド・起動（JAVA_HOME=Java 17 で実行）
  expo-android:
    desc: Android でビルド＆起動（Java 17 使用。エミュレータ or 実機を接続してから）
    cmds:
      - |
        export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null) || true
        npx expo run:android

  # 実機用: EXPO_PUBLIC_API_URL に PC の LAN IP を設定（実機と PC は同じ Wi‑Fi に接続すること）
  # 環境構築ののち Android Development Build をビルド＆起動。実機を接続してから実行すること。
  # 毎回 DB をゼロから構築するため、docker-compose down -v でボリューム削除してから up
  dev-up:
    desc: 実機用 - 環境構築（LAN IP）＋ .env.expo.local 更新 ＋ Android ビルド＆起動
    cmds:
      - pnpm supabase start
      - docker-compose down -v
      - |
        eval "$(node scripts/supabase-env-for-compose.mjs)" && docker-compose up -d
      - |
        echo "DB 起動待機ののちマイグレーション実行..."
        sleep 3
        cd backend && DATABASE_URL=postgresql://postgres:postgres@localhost:${DB_PORT:-5432}/sleepsupport uv run alembic upgrade head
      - node scripts/write-expo-env.mjs
      - |
        echo ""
        echo "[実機用] API: http://localhost:${API_PORT:-8000}  Supabase Studio: http://127.0.0.1:54323"
        echo "Android ビルド＆起動します（実機を接続済みにしてください）。"
        echo "WiFi を変えたら task dev-up を再実行してください。"
      - |
        export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null) || true
        npx expo run:android

  # エミュレータ用: EXPO_PUBLIC_API_URL を 10.0.2.2 に固定（Android エミュレータからホスト PC へ接続）
  # 環境構築ののち Android Development Build をビルド＆起動。エミュレータを起動してから実行すること。
  # 毎回 DB をゼロから構築するため、docker-compose down -v でボリューム削除してから up
  # Network request failed になる場合は docs/troubleshooting-emulator-network.md を参照（Metro を止めてから実行すること）
  dev-up-emulator:
    desc: エミュレータ用 - 環境構築（10.0.2.2）＋ .env.expo.local 更新 ＋ Android ビルド＆起動
    cmds:
      - pnpm supabase start
      - docker-compose down -v
      - |
        eval "$(node scripts/supabase-env-for-compose.mjs)" && docker-compose up -d
      - |
        echo "DB 起動待機ののちマイグレーション実行..."
        sleep 3
        cd backend && DATABASE_URL=postgresql://postgres:postgres@localhost:${DB_PORT:-5432}/sleepsupport uv run alembic upgrade head
      - EXPO_PUBLIC_API_URL=http://10.0.2.2:8000 node scripts/write-expo-env.mjs
      - |
        echo ""
        echo "[エミュレータ用] API: http://10.0.2.2:${API_PORT:-8000}  Supabase: http://10.0.2.2:54321"
        echo "Android ビルド＆起動します（エミュレータを起動済みにしてください）。"
        echo "Network request failed のときは Metro を止めてから再実行するか、docs/troubleshooting-emulator-network.md を参照。"
      - |
        export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null) || true
        npx expo run:android

  # バックエンドテスト実行（uv で pytest）。DB は別途起動済みであること
  test:
    desc: バックエンドのテストを実行（DB は起動済みであること）
    dir: backend
    cmds:
      - uv run pytest tests/ -v

  # DB を起動してからバックエンドの統合テストを実行（DB 利用テストを簡単に実行）
  test:db:
    desc: DB を起動してからバックエンドのテストを実行
    cmds:
      - docker-compose up -d db
      - |
        echo "DB 起動待機..."
        sleep 5
      - |
        cd backend && DATABASE_URL=postgresql://postgres:postgres@localhost:${DB_PORT:-5432}/sleepsupport uv run pytest tests/ -v

  # 開発環境をまとめて停止
  dev-down:
    desc: docker-compose と Supabase を停止
    cmds:
      - docker-compose down
      - pnpm supabase stop
